In [2]:
import numpy as np

In [2]:
l  = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
a =  np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
[i for i in a]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
[i+3 for i in a]

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [10]:
a+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
import random

In [13]:
l = [[random.randint(10,100) for i in range(3)] for i in range(7)]
l

[[92, 92, 48],
 [11, 83, 94],
 [46, 35, 61],
 [41, 18, 78],
 [23, 75, 45],
 [85, 51, 100],
 [49, 97, 45]]

In [21]:
A = np.random.randint(40,100,size=(7,3))
A

array([[92, 78, 67],
       [42, 99, 58],
       [79, 95, 97],
       [93, 70, 93],
       [77, 60, 72],
       [62, 68, 80],
       [93, 74, 54]])

In [22]:
A-10

array([[82, 68, 57],
       [32, 89, 48],
       [69, 85, 87],
       [83, 60, 83],
       [67, 50, 62],
       [52, 58, 70],
       [83, 64, 44]])

In [23]:
A**2

array([[8464, 6084, 4489],
       [1764, 9801, 3364],
       [6241, 9025, 9409],
       [8649, 4900, 8649],
       [5929, 3600, 5184],
       [3844, 4624, 6400],
       [8649, 5476, 2916]], dtype=int32)

In [24]:
import random

In [39]:
l = [[random.randint(40,100)for i in range(5)] for i in range(7)]
l

[[95, 47, 47, 65, 62],
 [60, 98, 50, 41, 49],
 [52, 40, 46, 75, 67],
 [42, 81, 63, 80, 89],
 [68, 89, 44, 84, 68],
 [63, 99, 58, 56, 42],
 [93, 79, 81, 82, 85]]

In [30]:
[max(i) for i in l]

[97, 97, 98, 95, 83, 100, 95]

In [31]:
A = np.random.randint(40,100,size=(7,5))

In [32]:
A

array([[44, 83, 41, 87, 75],
       [68, 86, 44, 94, 43],
       [46, 58, 61, 63, 71],
       [58, 99, 44, 93, 59],
       [86, 88, 46, 91, 65],
       [68, 81, 43, 94, 49],
       [74, 40, 41, 50, 92]])

In [40]:
A.max()

99

In [46]:
x =np.random.randint(10,100,size=(7,7))
x

array([[27, 51, 50, 37, 61, 18, 81],
       [41, 20, 18, 38, 34, 26, 22],
       [57, 44, 89, 90, 34, 45, 19],
       [99, 78, 88, 30, 10, 82, 74],
       [17, 18, 99, 98, 36, 71, 39],
       [15, 76, 90, 47, 87, 90, 76],
       [90, 50, 75, 84, 23, 96, 98]])

In [47]:
A.max(axis=1)

array([87, 94, 71, 99, 91, 94, 92])

In [48]:
L = list(range(100000))
len(L)

100000

In [49]:
L[0:20]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [50]:
A = np.arange(100000)
A.size

100000

In [51]:
A[0:20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
import sys

In [54]:
sys.getsizeof(A)

400104

In [1]:
A = np.random.randint(3,30,size=(2,3,4))

NameError: name 'np' is not defined

In [65]:
A

array([[[24, 16, 16, 20],
        [18,  7, 20,  9]],

       [[ 3, 26, 10, 26],
        [ 6,  8, 11, 23]]])

In [71]:
A.sum()

409

In [74]:
A.sum(axis=2)

array([[70, 82, 62],
       [79, 59, 57]])

In [75]:
A

array([[[11,  9, 26, 24],
        [10, 29, 22, 21],
        [19, 20, 13, 10]],

       [[19, 11, 20, 29],
        [ 7, 18, 25,  9],
        [16,  5, 28,  8]]])

In [78]:
A[0]

array([[11,  9, 26, 24],
       [10, 29, 22, 21],
       [19, 20, 13, 10]])

In [79]:
A[0,1,1]

29

In [82]:
import random
ls_names = ["emma","blessie","yehiva","shankar","likith","prasanth","john","elshadai","ajay","joshna","vicky","venu","hema","potti"]
names = random.sample(ls_names,10)
scores = [[random.randint(50,100) for i in range(5)] for i in range(10)]
marks = dict(zip(names,scores))
marks

{'john': [72, 54, 80, 60, 74],
 'prasanth': [78, 69, 67, 73, 67],
 'emma': [91, 100, 80, 92, 97],
 'yehiva': [95, 56, 71, 72, 97],
 'joshna': [95, 69, 75, 80, 59],
 'likith': [79, 50, 56, 84, 74],
 'shankar': [54, 74, 74, 50, 64],
 'ajay': [88, 66, 83, 76, 53],
 'blessie': [92, 74, 88, 83, 72],
 'potti': [98, 60, 65, 74, 68]}

In [83]:
import pandas as pd 

In [85]:
pd.DataFrame(marks)

john  prasanth  emma  yehiva  joshna  likith  shankar  ajay  blessie  potti
0    72        78    91      95      95      79       54    88       92     98
1    54        69   100      56      69      50       74    66       74     60
2    80        67    80      71      75      56       74    83       88     65
3    60        73    92      72      80      84       50    76       83     74
4    74        67    97      97      59      74       64    53       72     68

In [86]:
def get_summary(ls):
    return min(ls)

In [87]:
get_summary([51,91,78,66,52])

51

In [88]:
marks

{'john': [72, 54, 80, 60, 74],
 'prasanth': [78, 69, 67, 73, 67],
 'emma': [91, 100, 80, 92, 97],
 'yehiva': [95, 56, 71, 72, 97],
 'joshna': [95, 69, 75, 80, 59],
 'likith': [79, 50, 56, 84, 74],
 'shankar': [54, 74, 74, 50, 64],
 'ajay': [88, 66, 83, 76, 53],
 'blessie': [92, 74, 88, 83, 72],
 'potti': [98, 60, 65, 74, 68]}

In [89]:
def get_summary(ls):
    return min(ls),sum(ls)/len(ls),max(ls)

In [91]:
get_summary([10,20,30])

(10, 20.0, 30)

In [92]:
for i in marks.items():
    print(i)

('john', [72, 54, 80, 60, 74])
('prasanth', [78, 69, 67, 73, 67])
('emma', [91, 100, 80, 92, 97])
('yehiva', [95, 56, 71, 72, 97])
('joshna', [95, 69, 75, 80, 59])
('likith', [79, 50, 56, 84, 74])
('shankar', [54, 74, 74, 50, 64])
('ajay', [88, 66, 83, 76, 53])
('blessie', [92, 74, 88, 83, 72])
('potti', [98, 60, 65, 74, 68])


In [93]:
for i,j in marks.items():
    print(i,j)

john [72, 54, 80, 60, 74]
prasanth [78, 69, 67, 73, 67]
emma [91, 100, 80, 92, 97]
yehiva [95, 56, 71, 72, 97]
joshna [95, 69, 75, 80, 59]
likith [79, 50, 56, 84, 74]
shankar [54, 74, 74, 50, 64]
ajay [88, 66, 83, 76, 53]
blessie [92, 74, 88, 83, 72]
potti [98, 60, 65, 74, 68]


In [94]:
def get_summary(ls):
    return min(ls),sum(ls)/len(ls),max(ls)
for i,j in marks.items():
    print(i,get_summary(j))

john (54, 68.0, 80)
prasanth (67, 70.8, 78)
emma (80, 92.0, 100)
yehiva (56, 78.2, 97)
joshna (59, 75.6, 95)
likith (50, 68.6, 84)
shankar (50, 63.2, 74)
ajay (53, 73.2, 88)
blessie (72, 81.8, 92)
potti (60, 73.0, 98)


In [95]:
def get_summary(ls):
    return min(ls),sum(ls)/len(ls),max(ls)

In [96]:
get_summary([10,20,30])

(10, 20.0, 30)

In [97]:
for i,j in marks.items():
    print(i,min(j),sum(j)/len(j),max(j))

john 54 68.0 80
prasanth 67 70.8 78
emma 80 92.0 100
yehiva 56 78.2 97
joshna 59 75.6 95
likith 50 68.6 84
shankar 50 63.2 74
ajay 53 73.2 88
blessie 72 81.8 92
potti 60 73.0 98


In [99]:
import pywhatkit

ModuleNotFoundError: No module named 'pywhatkit'